name: budibase
services:
  server:
    image: budibase.docker.scarf.sh/budibase/apps:latest
    container_name: budibase-server
    hostname: budibase-server
    restart: always
    pull_policy: always
    environment:
      - BB_ADMIN_USER_EMAIL=budibase@example.com
      - BB_ADMIN_USER_PASSWORD=passwOrd123456
      - PORT=4002
      - SELF_HOSTED=1
      - LOG_LEVEL=info
      - ENABLE_ANALYTICS=true
      - BUDIBASE_ENVIRONMENT=PRODUCTION
      - REDIS_URL=budibase-redis:6379
      - MINIO_URL=http://budibase-minio:9000
      - WORKER_URL=http://budibase-worker:4003
      - COUCH_DB_URL=http://budibase-couchdb:5984
      - JWT_SECRET=${JWT_SECRET:-Igtbi7Et3pmHo5PSDezi43aZT00FqoWN1fJWqe5yuVlQbmrCP7voa9EVdWx4gjxv}
      - API_ENCRYPTION_KEY=${API_ENCRYPTION_KEY:-Igtbi7Et3pmHo5PSDezi43aZT00FqoWN1fJWqe5yuVlQbmrCP7voa9EVdWx4gjxv}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY:-QYAifWEyCTJJmxgAR7wlA5GUbctrnrQPabB7Y7xAwXVi0HiDyseWSi7a3HsJDW7NybKEmQJwAMxvubblNcwhJhuBCFESzBd34MmjObnsp54e8hYagHuPnN6g4qhlmd81}
    depends_on:
      - worker
      - redis
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://budibase-app:4002'
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 10s
    networks:
      - budibase

  worker:
    image: budibase.docker.scarf.sh/budibase/worker:latest
    container_name: budibase-worker
    hostname: budibase-worker
    restart: always
    pull_policy: always
    environment:
      - PORT=4003
      - SELF_HOSTED=1
      - CLUSTER_PORT=10000
      - REDIS_URL=budibase-redis:6379
      - APPS_URL=http://budibase-app:4002
      - MINIO_URL=http://budibase-minio:9000
      - COUCH_DB_URL=http://budibase-couchdb:5984
      - JWT_SECRET={JWT_SECRET:-Igtbi7Et3pmHo5PSDezi43aZT00FqoWN1fJWqe5yuVlQbmrCP7voa9EVdWx4gjxv}
      - API_ENCRYPTION_KEY={API_ENCRYPTION_KEY:-Igtbi7Et3pmHo5PSDezi43aZT00FqoWN1fJWqe5yuVlQbmrCP7voa9EVdWx4gjxv}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY:-QYAifWEyCTJJmxgAR7wlA5GUbctrnrQPabB7Y7xAwXVi0HiDyseWSi7a3HsJDW7NybKEmQJwAMxvubblNcwhJhuBCFESzBd34MmjObnsp54e8hYagHuPnN6g4qhlmd81}
    depends_on:
      - redis
      - minio
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://budibase-worker:4003'
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 10s
    networks:
      - budibase

  proxy:
    image: budibase.docker.scarf.sh/budibase/proxy:latest
    container_name: budibase-proxy
    hostname: budibase-proxy
    restart: always
    pull_policy: always
    environment:
      - SERVICE_FQDN_BUDIBASE_10000
      - PROXY_RATE_LIMIT_WEBHOOKS_PER_SECOND=10
      - PROXY_RATE_LIMIT_API_PER_SECOND=20
      - APPS_UPSTREAM_URL=http://budibase-app:4002'
      - MINIO_UPSTREAM_URL=http://budibase-minio:9000
      - WORKER_UPSTREAM_URL=http://budibase-worker:4003
      - COUCHDB_UPSTREAM_URL=http://budibase-couchdb:5984
      - RESOLVER=172.17.0.1
    ports:
      - '172.17.0.1:59061:10000'
    depends_on:
      - app
      - minio
      - worker
      - couchdb
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:10000/'
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 10s
    networks:
      - budibase

  minio:
    image: minio/minio
    container_name: budibase-minio
    hostname: budibase-minio
    restart: always
    pull_policy: always
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_BROWSER=off
    volumes:
      - /var/lib/srv/$USER/docker/budibase/apps/latest/rootfs/data/minio:/data
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - budibase

  couchdb:
    image: budibase/couchdb:latest
    container_name: budibase-couchdb
    hostname: budibase-couchdb
    restart: always
    pull_policy: always
    environment:
      - TARGETBUILD=docker-compose
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:5984/'
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 10s
    volumes:
      - /var/lib/srv/$USER/docker/budibase/apps/latest/rootfs/data/db/couchdb:/opt/couchdb/data
    networks:
      - budibase

  redis:
    image: redis:latest
    container_name: budibase-redis
    hostname: budibase-redis
    restart: always
    pull_policy: always
    command: 'redis-server'
    volumes:
      - /var/lib/srv/$USER/docker/budibase/apps/latest/rootfs/data/db/redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 10s
    networks:
      - budibase

networks:
  budibase:
    name: budibase
    external: false
